version: "3"
services:
  csr-db:
    image: "postgres:14-alpine"
    container_name: csr-db
    environment:
      - POSTGRES_USER=csr
      - POSTGRES_DB=csr
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -p 5432
    ports:
      - "5432:5432"
    networks:
      - csr_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U csr -p 5432" ]
      interval: 2s
      timeout: 1s
      retries: 5

  csr-be:
    image: csr-be
    build:
      context: csr-be/
      dockerfile: Dockerfile
    depends_on:
      - csr-db
    ports:
      - "8080:8080"
    networks:
      - csr_network
    command: "go run ./cmd/swagger/"
  csr-fe:
    image: csr-fe
    build:

      context: csr-fe/
      dockerfile: Dockerfile
    depends_on:
      - csr-db
    ports:
      - "8081:8080"
    networks:
      - csr_network

networks:
  csr_network:
